Autama/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as main_page_views  # from directory: Autama import view (the views.py file in this directory)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', main_page_views.FindMatches.as_view()),
    # Include all auth views
    url('^', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls, name="admin"),
    path('about/', main_page_views.about, name="about"),
    path('accounts/', include('accounts.urls')),
    path('FindMatches/', main_page_views.FindMatches.as_view(), name="FindMatches"),
    path('MyMatches/', main_page_views.MyMatches.as_view(), name="MyMatches"),
    path('UnMatch/<int:pk>/', main_page_views.unmatch_autama, name="UnMatch"),
    path('Match/<int:pk>/', main_page_views.match_autama, name="Match"),
    path('Chat/', main_page_views.chat_main_page, name="Chat_homepage"),
    path('Chat/<int:pk>/', main_page_views.Chat.as_view(), name="Chat"),
    path('logout/', main_page_views.LogoutView.as_view(), name="logout"),
    path('AutamaProfiles/', include('AutamaProfiles.urls')),
    path('MyClaims/', main_page_views.MyClaims.as_view(), name="MyClaims"),
    path('MyClaims/<int:pk>/', main_page_views.MyClaims.as_view(), name="unclaim"),
    path('unclaim_from_chat/<int:pk>/', main_page_views.unclaim_from_chat, name="unclaim_from_chat"),
    path('PrivacyPolicy/', main_page_views.PrivacyPolicy, name="PrivacyPolicy"),
    path('testdata/', main_page_views.testdata,),
    path('api/', include('API_tastypy.urls')),
    path('SeenAll/', main_page_views.SeenAll.as_view(), name="SeenAll"),
    path('MyAutamas/', main_page_views.MyAutamas.as_view(), name='MyAutamas'),
    path('CreateAutama/', main_page_views.CreateAutama.as_view(), name='CreateAutama'),
    path('send_report_email/', main_page_views.SendReportEmail.as_view(), name='SendReportEmail'),
    path('send_feedback_email/', main_page_views.SendFeedbackEmail.as_view(), name='SendFeedbackEmail'),
    path('Preview/<int:pk>/', main_page_views.Preview.as_view(), name="Preview"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AutamaProfiles/urls.py
from django.urls import path, include
from . import views as AutamaProfile_views


app_name = 'AutamaProfiles'

urlpatterns = [
    path('', AutamaProfile_views.browse, name='browse'),

    path('register/', AutamaProfile_views.register_autama, name='register_autama'),
    path('<int:pk>-<slug:slug>/', AutamaProfile_views.profile, name='profile'),
    path('claim/', AutamaProfile_views.claim, name='claim'),
    path('inprogress/', AutamaProfile_views.autama_in_progress, name='autama_in_progress'),
]

Automa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.homepage, name='homepage'),
    path('accounts/', include('accounts.urls'))
]

api/urls.py
from django.urls import include, path
from api.routers import OptionalSlashRouter
from rest_framework.authtoken.views import obtain_auth_token
from . import views

# NOTE: URL patterns specify endpoints & where they go to

router = OptionalSlashRouter()
router.register(r'User', views.UserViewSet)  # User info
router.register(r'Autama', views.AutamaViewSet)  # Autama info
router.register(r'Matches', views.MatchesViewSet)  # Matches
router.register(r'Messages', views.MessagesViewSet)  # Messages between user and Autama
# TODO: filter things using matchID, from the Matches model ^^


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('login/', obtain_auth_token, name='login'),  # 'login' or 'login/' ? also,  Webapp/login/
]

AutamaProfiles/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


class AutamaGeneral(models.Model):
    currentCount = models.IntegerField() # Index of current picture's spot
    totalCount = models.IntegerField(default=200) # Total amount of pictures
    autamaLimit = models.IntegerField(default=10) # Maximum autamas allowed for users to create
    autamaInProcess = models.IntegerField(default=0) # number of autama currently being produced via mass produce

    def __str__(self):
        return '{currentCount} {totalCount}'.format(currentCount=self.currentCount, totalCount=self.totalCount)


class AutamaProfile(models.Model):
    creator = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='Images', blank=False)
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)
    nummatches = models.IntegerField(default=0)
    owner = models.CharField(max_length=100, default='FREE')
    pickle = models.CharField(max_length=100, default='PICKLE')
    interest1 = models.CharField(max_length=100)
    interest2 = models.CharField(max_length=100)
    interest3 = models.CharField(max_length=100)
    interest4 = models.CharField(max_length=100)
    interest5 = models.CharField(max_length=100)
    interest6 = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, null=True, blank=True, default='')
    report_count = models.IntegerField(default=0)

    def __str__(self):
        return '{pk} {first} {last}'.format(pk=self.pk, first=self.first, last=self.last)

    def get_slug(self):
        slug = '{} {}'.format(self.first, self.last)
        return slugify(slug)

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk, 'slug': self.get_slug()})

AutamaProfiles/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.forms import ModelForm
from AutamaProfiles.models import AutamaProfile, AutamaGeneral
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
import json
from Nucleus.pancake import Pancake
from Nucleus.bacon import Bacon


class AutamaForm(ModelForm):
    class Meta:
        model = AutamaProfile
        fields = ['creator', 'picture', 'first', 'last', 'interest1', 'interest2', 'interest3', 'interest4', 'interest5', 'interest6']  # interests did exist here.


@login_required
def register_autama(request):
    if request.method == 'POST':
        form = AutamaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('about')

    else:
        form = AutamaForm()

    return render(request, "AutamaProfiles/register.html", {'form': form})


def profile(request, pk, slug):
    a_profile = get_object_or_404(AutamaProfile, pk=pk)
    return render(request, 'AutamaProfiles/autama_profile.html', {'profile': a_profile})


def browse(request):
    profiles = AutamaProfile.objects.all()
    return render(request, 'AutamaProfiles/browse.html', {'profiles': profiles})


def claim(request):
    a = request.POST.get("autama_id")
    profile = AutamaProfile.objects.get(pk=a)
    #profile.nummatches += 1
    profile.save()
    data = {'creator': profile.creator,
            'match_num': profile.nummatches}
    return HttpResponse(content=json.dumps(data),content_type='json/application')


# A function to create a new Autama profile. origin is the username of the user the Autama was based off
def create_autama_profile(personality: list, creator: str = "Happy Slackers", origin: str = "Happy Slackers"):
    pancake = Pancake()  # For handling name generating
    first = pancake.generate_first_name()
    last = pancake.generate_last_name()
    create_custom_autama(creator, first, last, origin, personality)


# A function to create custom Autama
def create_custom_autama(creator: str, first: str, last: str, origin: str, personality: list):
    REQUIRED = 6  # The required amount of traits
    bacon = Bacon()
    # Make sure personality does not have "my name is" traits
    checked_personality = bacon.check_personality(personality)
    amount = len(checked_personality)

    # Make sure personality has the required amount of traits
    if amount == REQUIRED:
        # Get meta data on Autama Images and generate path for current autama picture
        picture = get_picture_name()

        first_name = first.rstrip()
        first_name = first_name.lstrip()
        first_name = first_name.capitalize()

        last_name = last.rstrip()
        last_name = last_name.lstrip()
        last_name = last_name.capitalize()

        interest1 = add_period(checked_personality[0])
        interest2 = add_period(checked_personality[1])
        interest3 = add_period(checked_personality[2])
        interest4 = add_period(checked_personality[3])
        interest5 = add_period(checked_personality[4])
        interest6 = add_period(checked_personality[5])

        new_autama = AutamaProfile.objects.create(creator=creator, picture=picture, first=first_name, last=last_name,
                                                  pickle=origin,
                                                  interest1=interest1, interest2=interest2,
                                                  interest3=interest3, interest4=interest4,
                                                  interest5=interest5, interest6=interest6)
        new_autama.save()


# A function to check if an interest ends  with a punctuation mark. If it does not, it will add a period.
# Also capitalizes first letter
def add_period(interest: str):
    i = interest.rstrip()
    i = i.lstrip()
    i = i.capitalize()

    period = i.endswith(".")
    question_mark = i.endswith("?")
    exclamation_point = i.endswith("!")

    # Add period if interest does not end with a punctuation mark
    if not period and not question_mark and not exclamation_point:
        revised_interest = i + "."
        return revised_interest
    else:
        return i


# A function to get meta data on Autama Images by first checking if it exists and then creating one if it doesn't
def get_meta():
    if not AutamaGeneral.objects.exists():
        # If queryset is empty, create a new query
        gen = AutamaGeneral()
        gen.currentCount = 1
        gen.totalCount = 100
        gen.autamaLimit = 10
        gen.autamaInProcess = 0
        gen.save()

    # Get and return meta data
    meta_autama = AutamaGeneral.objects.first()
    return meta_autama


# A function to get a file name for a picture
def get_picture_name():
    meta_autama = get_meta()
    file_name = "a" + str(meta_autama.currentCount) + ".png"
    meta_autama.currentCount += 1
    meta_autama.save()
    return file_name


# A function to get the value of the maximum amount of Autamas an user can create
def get_my_autama_limit():
    meta_autama = get_meta()
    limit = meta_autama.autamaLimit
    return limit


@login_required()
def autama_in_progress(request):
    if request.method == 'GET':
        ag = get_meta()
        return JsonResponse({'inprogress': ag.autamaInProcess})
    if request.method == 'POST':
        return JsonResponse({'post': 'testing'})

templates/AutamaProfiles/autama_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <div>
        <form action="massproduce/" method="POST">
            {% csrf_token %}
                <button type="submit">Mass-produce</button>
        </form>
    </div>
    <br />
    {{ block.super }}
{% endblock %}

templates/AutamaProfiles/autama_profile.html
{% extends 'base.html' %}


{% block csstyle %}
    <style>
        div.profile{
            height: 450px;
            width: 350px;
            border: 2px solid #d4cce0;
            box-shadow: 10px 10px 5px #888888;
            border-radius: 15px;
            float: none;
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 15%;
            margin-bottom: auto;
            overflow: scroll;
        }

        div.profile > img{
            height: 370px;
            width: 350px;
            border-radius: 15px;
        }

        div.profile > div:nth-child(1){
            background-color: #9e9e9e59;
        }

        div.profile > div:nth-child(2){
            margin-top: 30px;
        }

        .name{
            background: linear-gradient(90deg, #6737E5 50%, #B93FA3 80%);
            -webkit-background-clip: text;
            color: transparent;
        }

        .intro{
            margin-top: auto;
            float: left;
            height:45px;
            border-radius: 3px;
            background: linear-gradient(90deg, #6737E5 50%, #B93FA3 80%);
            text-align: center;
            vertical-align: center;
            margin-left: 15px;

        }

        .report_box {
            display: none;
        }

    </style>
{%  endblock %}

{% block content %}
    <h2 class="intro">
        Autama Profile
    </h2>
    <div style="width: 80%; margin-top: 50px; margin: auto; ">

        <div class="profile">
            <img src="{{ profile.picture.url }}">
            <span class="name" style="font-weight: bold; font-size: xx-large; margin-left: 10px">{{profile.first }}</span>

            <div style="font-size: x-large; color: black; margin-left: 10px; margin-bottom: 5px">
                Introduce
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px">
                Autama ID: a{{ profile.pk }}
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px">
                Interests: {{ profile.interest1 }}, {{ profile.interest2 }}, {{ profile.interest3 }}
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px">
                Owner: {{ profile.owner }}
            </div>

            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px">
                Pickle: {{ profile.pickle }}
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px" id="creator">
                Creator: {{ profile.creator }}
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px" id="match_number">
                Match number: {{ profile.nummatches }}
            </div>
            <div style="font-size: medium; color: gray; margin-left: 10px; margin-bottom: 5px">
                
                <button class="btn btn-default btn-lg" style="background-image: linear-gradient(90deg, rgba(252, 79, 108, 1) 50%, rgba(245, 114, 88, 1) 70%);" onclick="share_robot()">Share</button>
            </div>

        </div>

    </div>


    <!-- start of report code here -->

    <br><br><br>
    <input onclick="showReport()" style="background-image: linear-gradient(90deg, #6737E5 50%, #B93FA3 80%); border-style: none;" class="btn btn-info" style="width:100px;position: absolute;top: 50%;transform: translateY(-50%)translateX(-50%);left: 50%;" name="report" value="Report">


    <!-- jQuery dialog code here: https://stackoverflow.com/questions/40939099/jquery-form-submit-with-confirmation-in-a-modal -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


    <div id="dialog-confirm" title="Report submitted, thank you!">
        <p>Would you like to provide additional feedback?</p>
    </div>

    <script>
        function showReport() {
            if (document.getElementById("report").style.display != "block") {
                div = document.getElementById("report").style.display="block";
            } else {
                div = document.getElementById("report").style.display="none";
            }
        }

        function hideReport() {
            div = document.getElementById("report").style.display="none";
        }

        $(function() {
            $("#dialog-confirm").dialog({
                resizable: false,
                height: 180,
                autoOpen: false,
                width: 330,
                modal: true,
                buttons: {
                    "Yes": function() {
                        $('#reportform').submit();
                        window.location.replace("http://127.0.0.1:8000/about/");
                    },
                    No: function() {
                        $(this).dialog("close");
                        hideReport();
                    }
                }
            });

            $('#submitReport').on('click', function(e) {
                $("#dialog-confirm").dialog('open');
            });
        });
    </script>

    <!-- https://www.tutorialspoint.com/How-to-Create-a-Multi-line-Text-Input-Text-Area-In-HTML -->
    <div class="report_box" id="report">
        <!-- <form action="???" method="post"> -->
        <!-- include csrf_token here -->
        <h1>Report Autama</h1>
        <form id="reportform">
            <input style="margin: 15px 15px 15px 15px" type="checkbox" id="option1" name="option1" value="Option 1">
            <label for="option1"> Inappropriate content</label><br>
            <input style="margin: 15px 15px 15px 15px" type="checkbox" id="option2" name="option2" value="Option 2">
            <label for="option2"> Autama is broken</label><br>
            <input style="margin: 15px 15px 15px 15px" type="checkbox" id="option3" name="option3" value="Option 3">
            <label for="option3"> Autama is boring</label><br>
            <input style="margin: 15px 15px 15px 15px" type="checkbox" id="option4" name="option4" value="Option 4">
            <label for="option4"> Other</label><br><br>

            <!-- jQuery dialog-confirm code -->
            <input type="hidden" name="submitReport" value="Submit"/>
            <input type="button" id="submitReport" value="Submit"/>

            <button onclick="hideReport()"/>Close</button>
        </form>
    </div>
    <!-- end of report code -->

{% endblock %}

{% block js %}
    <script type="application/javascript">
        function copyText(text) {
            var textarea = document.createElement("input");
            var currentFocus = document.activeElement;
            document.body.appendChild(textarea);
            textarea.value = text;
            textarea.focus();
            if(textarea.setSelectionRange)
                textarea.setSelectionRange(0, textarea.value.length);
            else
                textarea.select();
            try {
                var flag = document.execCommand("copy");
            } catch(eo) {
                var flag = false;
            }
            document.body.removeChild(textarea);
            currentFocus.focus();
            return flag;
        }

        function share_robot() {

            var s = "http://127.0.0.1:8000/AutamaProfiles/{{ profile.autamaid }}-{{ profile.first }}-{{ profile.last }}/";
            copyText(s);
            alert("Copy successful！");
        }
    </script>
{% endblock %}

templates/AutamaProfiles/browse.html
{% extends 'base.html' %}

{% block csstyle %}
    <style>
    .container {
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
            flex-wrap: wrap;
            align-items: flex-start;
        }

    h1 {
        background: linear-gradient(to right bottom, rgba(252, 79, 108, 1) 50%, rgba(245, 114, 88, 1) 70%);
        -webkit-background-clip: text;
        color: transparent;
    }

    span{
        margin-left: 70px;
        font-family: "Open Sans", "Helvetica", sans-serif;
        font-weight: bold;
        font-size: xx-large;
        background: linear-gradient(to right, rgba(252, 79, 108, 1) 50%, rgba(245, 114, 88, 1) 70%);
        -webkit-background-clip: text;
        color: transparent;
    }
    </style>

{% endblock %}

{% block content %}
<body style=" margin-left: 27px; margin-top: 70px;">
    <h1>Meet the Autamas</h1>
    <div class="profiles, container">
        {% for profile in profiles %}

            <div class="profiles" style="padding: 10px; margin: 1px">
                <a href="{% url 'AutamaProfiles:profile' pk=profile.pk slug=profile.get_slug %}">
                    <img class="img-responsive" src="{{ profile.picture.url }}" width="276" height="210">
                </a>
                <span> {{ profile.pk }} {{ profile.first }} {{profile.last}} </span>
            </div>

        {% endfor %}
    </div>
</body>
{% endblock %}

templates/AutamaProfiles/register.html
{% extends 'base.html' %}

{% block content %}
<body style="margin-top: 50px">
    <h1>Register your Autama here</h1>
    <form action="/AutamaProfiles/register/" enctype="multipart/form-data" method="post">
        {%csrf_token%}
        {{ form }}
        <input type="submit" value="create">
    </form>
</body>
{% endblock %}